# Generated by Django 2.2.5 on 2020-01-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test123',
            new_name='Test',
        ),
    ]
