# Generated by Django 2.2.5 on 2020-01-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_test_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
