# Generated by Django 2.2.5 on 2020-01-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_test_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='thing_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPEOF', models.CharField(max_length=50)),
                ('TXM', models.CharField(max_length=50)),
            ],
        ),
    ]
