# Generated by Django 2.2.5 on 2020-01-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_thing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing_info',
            name='WUPIN_NAME',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
